const ALL_POSTS = [
  {
    id:1,
    title:'Zustand로 React 상태 관리 쉽게 하기',
    desc:'Redux보다 훨씬 간단한 상태 관리 라이브러리 Zustand의 기본 개념과 store 생성, Devtools, persist, Immer 활용 방법까지 정리했습니다.',
    tags:['React','Zustand','State'],
    date:'2024-12-08',
    url:'posts/zustand.html',
  },
  {
    id:2,
    title:'공용 컴포넌트 설계 방법 정리 (Frontend Fundamentals)',
    desc:'변경하기 쉬운 프론트엔드 코드를 만들기 위한 가독성, 예측 가능성, 응집도, 결합도 기준을 정리했습니다.',
    tags:['Frontend','Architecture'],
    date:'2025-01-29',
    url:'posts/frontend-fundamentals.html',
  },
  { id:2,  title:'TypeScript 타입 추론의 모든 것', desc:'제네릭, 조건부 타입, infer 키워드까지 — 타입스크립트가 타입을 추론하는 방식을 깊게 파고들었습니다.', tags:['TypeScript'], date:'2026.02.20', read:'8 min' },
  { id:3,  title:'Next.js App Router 마이그레이션 후기', desc:'Pages Router에서 App Router로 이전하면서 겪은 시행착오와 얻은 교훈을 공유합니다.', tags:['Next.js','React'], date:'2026.02.10', read:'10 min' },
  { id:4,  title:'Tailwind CSS를 잘 쓰는 법', desc:'유틸리티 클래스가 많아질수록 관리가 어려워집니다. 컴포넌트 설계와 함께 효율적으로 사용하는 팁입니다.', tags:['CSS','Frontend'], date:'2026.01.30', read:'5 min' },
  { id:5,  title:'성능 최적화: 웹 Core Web Vitals 개선기', desc:'LCP, CLS, FID 수치를 실제로 어떻게 개선했는지 측정 도구와 함께 소개합니다.', tags:['Performance','Frontend'], date:'2026.01.22', read:'9 min' },
  { id:6,  title:'Zustand로 전역 상태 관리하기', desc:'Redux 없이도 충분합니다. 간결한 Zustand의 API와 미들웨어 활용법을 정리했습니다.', tags:['React','State'], date:'2026.01.14', read:'7 min' },
  { id:7,  title:'CSS Container Queries 실전 가이드', desc:'미디어 쿼리의 한계를 넘어서는 Container Queries — 브라우저 지원 현황과 실제 사용 예시를 담았습니다.', tags:['CSS'], date:'2026.01.05', read:'6 min' },
  { id:8,  title:'Vitest로 빠른 유닛 테스트 환경 만들기', desc:'Jest 대비 빠른 Vitest로 테스트 환경을 세팅하고 React Testing Library와 함께 쓰는 방법을 소개합니다.', tags:['Testing','TypeScript'], date:'2025.12.28', read:'7 min' },
  { id:9,  title:'Framer Motion 인터랙션 디자인 패턴', desc:'자연스러운 UI 애니메이션을 만드는 데 자주 사용하는 Motion 패턴들을 코드와 함께 정리했습니다.', tags:['React','CSS'], date:'2025.12.18', read:'8 min' },
  { id:10, title:'Git 협업 전략 — Trunk Based Development', desc:'Feature Branch 전략의 대안으로 주목받는 Trunk Based Development의 개념과 실전 적용 사례입니다.', tags:['Git'], date:'2025.12.10', read:'5 min' },
  { id:11, title:'접근성(a11y)을 고려한 컴포넌트 설계', desc:'ARIA, 키보드 탐색, 색상 대비까지 — 모두가 사용할 수 있는 웹을 만들기 위한 기초부터 심화까지.', tags:['Frontend','CSS'], date:'2025.12.02', read:'9 min' },
  { id:12, title:'Turbopack과 번들러의 미래', desc:'Webpack을 대체할 Turbopack이 실제로 얼마나 빠른지, 어떤 상황에서 도입할 수 있는지 살펴봤습니다.', tags:['Performance','Frontend'], date:'2025.11.25', read:'6 min' },
  { id:13, title:'서버 컴포넌트 vs 클라이언트 컴포넌트', desc:'Next.js에서 둘 중 무엇을 선택할지 판단하는 기준과 실제 사례를 통해 차이를 명확히 짚어봅니다.', tags:['Next.js','React'], date:'2025.11.18', read:'8 min' },
  { id:14, title:'Storybook 7 컴포넌트 문서화 가이드', desc:'디자인 시스템 구축에 필수적인 Storybook — 최신 버전의 CSF3 문법과 인터랙션 테스트를 소개합니다.', tags:['Frontend','Testing'], date:'2025.11.08', read:'7 min' },
  { id:15, title:'GraphQL + Apollo Client 입문', desc:'REST API와 다른 GraphQL의 사고 방식, Apollo Client로 데이터 fetching과 캐싱을 다루는 방법입니다.', tags:['Frontend','State'], date:'2025.10.30', read:'11 min' },
];